# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('pubsub', ['pubsub','internet','core','network','point-to-point','netanim'])
    obj.source = 'pubsub.cc'

